COUNTRIES = [
    {
        "iso2": "ES",
        "iso3": "ESP",
        "name": "Spain",
        "region": "Europe",
        "subregion": "Southern Europe",
        "currency": "EUR",
        "eu_member": True,
        "eurozone_member": True,
        "oecd_member": True,
        "labour_market_languages": ["Spanish"],
    },
    {
        "iso2": "PT",
        "iso3": "PRT",
        "name": "Portugal",
        "region": "Europe",
        "subregion": "Southern Europe",
        "currency": "EUR",
        "eu_member": True,
        "eurozone_member": True,
        "oecd_member": True,
        "labour_market_languages": ["Portuguese"],
    },
    {
        "iso2": "IE",
        "iso3": "IRL",
        "name": "Ireland",
        "region": "Europe",
        "subregion": "Northern Europe",
        "currency": "EUR",
        "eu_member": True,
        "eurozone_member": True,
        "oecd_member": True,
        "labour_market_languages": ["English"],
    },
]

SOURCES = [
    {
        "source_id": "UN_WPP",
        "name": "UN World Population Prospects",
        "organisation": "United Nations DESA Population Division",
        "base_url": "https://population.un.org/wpp",
        "priority": 1,
    },
    {
        "source_id": "IMF",
        "name": "IMF",
        "organisation": "International Monetary Fund",
        "base_url": "https://www.imf.org/external/datamapper/api/v2",
        "priority": 1,
    },
    {
        "source_id": "OECD",
        "name": "OECD",
        "organisation": "Organisation for Economic Co-operation and Development",
        "base_url": "https://sdmx.oecd.org/public/rest",
        "priority": 1,
    },
    {
        "source_id": "EUROSTAT",
        "name": "Eurostat",
        "organisation": "European Commission / Eurostat",
        "base_url": "https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0",
        "priority": 1,
    },
    {
        "source_id": "WORLD_BANK",
        "name": "World Bank",
        "organisation": "World Bank",
        "base_url": "https://api.worldbank.org/v2",
        "priority": 2,
    },
]

INDICATORS = [
    {
        "indicator_id": "intentional_homicide_rate",
        "source_indicator": "EUROSTAT:CRIM_OFF_CAT:ICCS0101",
        "name": "Police-recorded intentional homicides",
        "dimension": "safety",
        "unit": "per_100k_people",
        "interpretation_policy": "lower",
        "target_min": None,
        "target_max": None,
    },
    {
        "indicator_id": "pm25_premature_death_rate",
        "source_indicator": "EUROSTAT:SDG_11_52",
        "name": "Premature deaths attributable to PM2.5 exposure",
        "dimension": "environment",
        "unit": "per_100k_people",
        "interpretation_policy": "lower",
        "target_min": None,
        "target_max": None,
    },
    {
        "indicator_id": "household_price_level_index",
        "source_indicator": "EUROSTAT:PRC_PPP_IND",
        "name": "Household consumption price level index",
        "dimension": "prosperity",
        "unit": "index_eu27_2020_100",
        "interpretation_policy": "contextual",
        "target_min": None,
        "target_max": None,
    },
    {
        "indicator_id": "real_house_price_index",
        "source_indicator": "EUROSTAT:TIPSHO10",
        "name": "Real house price index (2015=100)",
        "dimension": "housing",
        "unit": "index_2015_100",
        "interpretation_policy": "lower",
        "target_min": None,
        "target_max": None,
    },
    {
        "indicator_id": "rent_price_index",
        "source_indicator": "EUROSTAT:PRC_HICP_AIND:CP041",
        "name": "Actual rent price index",
        "dimension": "housing",
        "unit": "index_annual_average",
        "interpretation_policy": "lower",
        "target_min": None,
        "target_max": None,
    },
    {
        "indicator_id": "housing_cost_overburden_rate",
        "source_indicator": "EUROSTAT:TESSI163",
        "name": "Housing cost overburden rate",
        "dimension": "housing",
        "unit": "percent",
        "interpretation_policy": "lower",
        "target_min": None,
        "target_max": None,
    },
    {
        "indicator_id": "tertiary_education_25_34",
        "source_indicator": "EUROSTAT:SDG_04_20",
        "name": "Tertiary educational attainment, ages 25–34",
        "dimension": "human_systems",
        "unit": "percent",
        "interpretation_policy": "higher",
        "target_min": None,
        "target_max": None,
    },
    {
        "indicator_id": "energy_import_dependency",
        "source_indicator": "EUROSTAT:NRG_IND_ID",
        "name": "Energy import dependency",
        "dimension": "strategic_resilience",
        "unit": "percent",
        "interpretation_policy": "contextual",
        "target_min": None,
        "target_max": None,
    },
    {
        "indicator_id": "median_age",
        "source_indicator": "UN_WPP:MedianAgePop",
        "name": "Median age of population",
        "dimension": "demography",
        "unit": "years",
        "interpretation_policy": "contextual",
        "target_min": None,
        "target_max": None,
    },
    {
        "indicator_id": "life_expectancy",
        "source_indicator": "UN_WPP:LEx",
        "name": "Life expectancy at birth",
        "dimension": "human_systems",
        "unit": "years",
        "interpretation_policy": "higher",
        "target_min": None,
        "target_max": None,
    },
    {
        "indicator_id": "real_gdp_growth",
        "source_indicator": "IMF:WEO:NGDP_RPCH",
        "name": "Real GDP growth (annual %)",
        "dimension": "prosperity",
        "unit": "percent",
        "interpretation_policy": "higher",
        "target_min": None,
        "target_max": None,
    },
    {
        "indicator_id": "imf_inflation_average",
        "source_indicator": "IMF:WEO:PCPIPCH",
        "name": "Inflation, average consumer prices (annual %)",
        "dimension": "prosperity",
        "unit": "percent",
        "interpretation_policy": "target_range",
        "target_min": 1.0,
        "target_max": 3.0,
    },
    {
        "indicator_id": "imf_unemployment_rate",
        "source_indicator": "IMF:WEO:LUR",
        "name": "Unemployment rate (IMF WEO)",
        "dimension": "productive_capacity",
        "unit": "percent",
        "interpretation_policy": "lower",
        "target_min": None,
        "target_max": None,
    },
    {
        "indicator_id": "gdp_per_hour_worked",
        "source_indicator": "OECD:DSD_PDB@DF_PDB:GDPHRS",
        "name": "GDP per hour worked (PPP, constant prices)",
        "dimension": "productive_capacity",
        "unit": "usd_ppp_per_hour",
        "interpretation_policy": "higher",
        "target_min": None,
        "target_max": None,
    },
    {
        "indicator_id": "population_total",
        "source_indicator": "SP.POP.TOTL",
        "name": "Population, total",
        "dimension": "demography",
        "unit": "persons",
        "interpretation_policy": "contextual",
        "target_min": None,
        "target_max": None,
    },
    {
        "indicator_id": "real_gdp",
        "source_indicator": "NY.GDP.MKTP.KD",
        "name": "GDP (constant 2015 US$)",
        "dimension": "productive_capacity",
        "unit": "constant_2015_usd",
        "interpretation_policy": "higher",
        "target_min": None,
        "target_max": None,
    },
    {
        "indicator_id": "real_gdp_per_capita",
        "source_indicator": "NY.GDP.PCAP.KD",
        "name": "GDP per capita (constant 2015 US$)",
        "dimension": "prosperity",
        "unit": "constant_2015_usd_per_person",
        "interpretation_policy": "higher",
        "target_min": None,
        "target_max": None,
    },
    {
        "indicator_id": "unemployment_rate",
        "source_indicator": "SL.UEM.TOTL.ZS",
        "name": "Unemployment, total (% of total labor force)",
        "dimension": "productive_capacity",
        "unit": "percent",
        "interpretation_policy": "lower",
        "target_min": None,
        "target_max": None,
    },
    {
        "indicator_id": "employment_population_ratio",
        "source_indicator": "SL.EMP.TOTL.SP.ZS",
        "name": "Employment to population ratio, 15+, total (%)",
        "dimension": "productive_capacity",
        "unit": "percent",
        "interpretation_policy": "higher",
        "target_min": None,
        "target_max": None,
    },
    {
        "indicator_id": "employment_rate_20_64",
        "source_indicator": "EUROSTAT:LFSI_EMP_A",
        "name": "Employment rate, ages 20–64 (%)",
        "dimension": "productive_capacity",
        "unit": "percent",
        "interpretation_policy": "higher",
        "target_min": None,
        "target_max": None,
    },
    {
        "indicator_id": "inflation_cpi",
        "source_indicator": "FP.CPI.TOTL.ZG",
        "name": "Inflation, consumer prices (annual %)",
        "dimension": "prosperity",
        "unit": "percent",
        "interpretation_policy": "target_range",
        "target_min": 1.0,
        "target_max": 3.0,
    },
    {
        "indicator_id": "inflation_hicp",
        "source_indicator": "EUROSTAT:PRC_HICP_AINR",
        "name": "HICP inflation, annual average (%)",
        "dimension": "prosperity",
        "unit": "percent",
        "interpretation_policy": "target_range",
        "target_min": 1.0,
        "target_max": 3.0,
    },
    {
        "indicator_id": "fertility_rate",
        "source_indicator": "SP.DYN.TFRT.IN",
        "name": "Fertility rate, total (births per woman)",
        "dimension": "demography",
        "unit": "births_per_woman",
        "interpretation_policy": "contextual",
        "target_min": None,
        "target_max": None,
    },
    {
        "indicator_id": "population_65_plus_share",
        "source_indicator": "SP.POP.65UP.TO.ZS",
        "name": "Population ages 65 and above (% of total)",
        "dimension": "demography",
        "unit": "percent",
        "interpretation_policy": "contextual",
        "target_min": None,
        "target_max": None,
    },
    {
        "indicator_id": "net_migration",
        "source_indicator": "SM.POP.NETM",
        "name": "Net migration",
        "dimension": "demography",
        "unit": "persons",
        "interpretation_policy": "contextual",
        "target_min": None,
        "target_max": None,
    },
    {
        "indicator_id": "public_debt_gdp",
        "source_indicator": "EUROSTAT:GOV_10DD_EDPT1",
        "name": "General government gross debt (% of GDP)",
        "dimension": "fiscal",
        "unit": "percent_gdp",
        "interpretation_policy": "contextual",
        "target_min": None,
        "target_max": None,
    },
]


COUNTRY_BY_ISO3 = {country["iso3"]: country for country in COUNTRIES}


def country_config(country_iso3: str) -> dict:
    key = country_iso3.upper()
    if key not in COUNTRY_BY_ISO3:
        raise ValueError(f"Unsupported country: {country_iso3}")
    return COUNTRY_BY_ISO3[key]


def world_bank_indicators() -> list[dict]:
    return [
        indicator
        for indicator in INDICATORS
        if ":" not in indicator["source_indicator"]
    ]
